version: "3.8"

services:
  prometheus:
    image: prom/prometheus:main
    container_name: terra-prometheus
    ports:
      - 9090:9090
    volumes:
      - ./docker/prometheus:/etc/prometheus
    restart: always

  node-exporter:
    image: prom/node-exporter
    container_name: terra-node-exporter
    restart: always

  victoriametrics:
    image: victoriametrics/victoria-metrics:latest
    container_name: terra-victoriametrics
    ports:
      - 9091:8428
    volumes:
      - ./docker/victoria-metrics:/victoria-metrics-data
    restart: always

  grafana:
    image: grafana/grafana:main
    container_name: terra-grafana
    ports:
      - 9092:3000
    volumes:
      - ./docker/grafana:/var/lib/grafana
    restart: always
